### ISSUE TITLE
Hint not found on 16-bit converted floating registers.

### ISSUE THREAD

**Issue by shibbo** [NeatMonster/AMIE#4]
The plugin does not seem to highlight 16-bit floating registers, as seen in the screenshot. They follow the same conventions as the normal 32-bit and 64-bit floating registers.

![image](https://user-images.githubusercontent.com/22485411/50404514-eae62f00-0776-11e9-9300-872776ed2a7f.png)

**Comment by NeatMonster** [comment]
Should be fixed by [this commit](https://github.com/NeatMonster/AMIE/commit/0e552a21e4fdbb3bd5471171c5d7d1cc9c9b024a). There is probably something better to do about it in the future.

![neon_registers](https://user-images.githubusercontent.com/775152/67502842-de787e80-f686-11e9-87d7-269840f124d1.PNG)
